# 配置端口
server:
  port: 80

# 配置 SpringBoot 应用
spring:
  application:
    name: ms-gateway
  cloud:
    # 配置网关
    gateway:
      # 服务发现策略
      discovery:
        locator:
          enabled: true # 开启配置注册中心进行路由功能
          lower-case-service-id: true # 将服务名称小写化
      # 路由规则
      routes:
        - id: ms-diners
          uri: lb://ms-diners
          predicates:
            - Path=/hello/**


# 注册进 Eureka
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka/
